//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesCannon.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public string emailPersona { get; set; }
        public string nombrePersona { get; set; }
        public string passwordPersona { get; set; }
        public int idPersona { get; set; }
    }
}
